//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerteBienV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD
    {
        public int id_card { get; set; }
        public string id_usuario { get; set; }
        public string estatus { get; set; }
        public string token { get; set; }
        public string trasaction_reference { get; set; }
        public string digitos { get; set; }
        public string fecha_expiracion { get; set; }
        public Nullable<System.DateTime> fecha_agregada { get; set; }
        public string comentario { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
