//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerteBienV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITAS()
        {
            this.PUNTUACION_PELUQUERIA = new HashSet<PUNTUACION_PELUQUERIA>();
            this.PUNTUACION_SERVICIOS = new HashSet<PUNTUACION_SERVICIOS>();
        }
    
        public int id_cita { get; set; }
        public string id_usuario { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_cita { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> hora { get; set; }
        public string comentario_cliente { get; set; }
        public string comentario_peluqueria { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTUACION_PELUQUERIA> PUNTUACION_PELUQUERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTUACION_SERVICIOS> PUNTUACION_SERVICIOS { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
    }
}
