// <auto-generated />
namespace VerteBienV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creando_SP_Busca_Servicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creando_SP_Busca_Servicio));
        
        string IMigrationMetadata.Id
        {
            get { return "202108031818479_Creando_SP_Busca_Servicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
