// <auto-generated />
namespace VerteBienV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Arreglando_columna_capacidadsimultanea : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Arreglando_columna_capacidadsimultanea));
        
        string IMigrationMetadata.Id
        {
            get { return "202105171501099_Arreglando_columna_capacidadsimultanea"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
