//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerteBienV1 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SP_Busca_Servicio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SP_Busca_Servicio() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerteBienV1.SP_Busca_Servicio", typeof(SP_Busca_Servicio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DROP PROCEDURE [dbo].[Buscar_Servicio].
        /// </summary>
        internal static string Borra_Filtro {
            get {
                return ResourceManager.GetString("Borra_Filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borra_Filtro.
        /// </summary>
        internal static string Borra_SP_Filtro {
            get {
                return ResourceManager.GetString("Borra_SP_Filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a create procedure [dbo].[Buscar_Servicio] (@dato varchar(100), @sector varchar(100))
        ///as
        ///begin
        ///
        ///Declare @id_servicio int
        ///Declare @id_usuario nvarchar(128)
        ///Declare @id_categoria int
        ///Declare @nombre_servicio varchar(100)
        ///Declare @descripcion varchar(max)
        ///Declare @precio_servicio decimal(12,2)
        ///Declare @tiempo decimal(12,2)
        ///Declare @imagenes varchar(max)
        ///Declare @estado varchar(10)
        ///
        ///	-- Tabla para almacenar los id de los servicio que se mostraran
        ///	 CREATE TABLE #id_servicios (
        ///	 id int identity pr [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Buscar_Servicio {
            get {
                return ResourceManager.GetString("Buscar_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar_Servicio.sql.
        /// </summary>
        internal static string Buscar_Servicio_Filtro {
            get {
                return ResourceManager.GetString("Buscar_Servicio_Filtro", resourceCulture);
            }
        }
    }
}
